name: Project build

on:
  push:

jobs:
  ci:
    name: Black and isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - run: pip install -r deployment/requirements-dev.txt
      - run: black --check deployment/src
      - run: isort deployment/src/*
      - uses: brpaz/hadolint-action@master

